project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - model.qmd
    
website:
  title: "DSA306 Group Project - Group 7"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - model.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

